[package]
name = "crossbeam"
version = "0.2.7"
authors = ["Aaron Turon <aturon@mozilla.com>"]
description = "Support for lock-free data structures, synchronizers, and parallel programming"
repository = "https://github.com/aturon/crossbeam"
documentation = "http://aturon.github.io/crossbeam-doc/crossbeam/"
readme = "README.md"
license = "Apache-2.0/MIT"

[features]
nightly = []

[dependencies]
criterion = {git = "https://github.com/japaric/criterion.rs.git"}

[dev-dependencies]
rand = "0.3"
